#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config{/log/nginx,/log/rtorrent,/log/rutorrent,/irssi/,/nginx,/php,/rtorrent/rtorrent_sess,/rutorrent/settings/users} \
	/config/rutorrent/profiles{/settings,/torrents,/users,/tmp} \
	/data{/completed,/downloading,/sessions,/watch} \
	/run{/nginx,/php} \
	/var/lib/nginx/tmp/client_body

mkdir -p /config/irssi/scripts/autorun && \
  cd /config/irssi/scripts && \
  wget --quiet -O autodl-irssi.zip https://github.com/autodl-community/autodl-irssi/releases/download/community-v1.62/autodl-irssi-community-v1.62.zip && \
  unzip -o autodl-irssi.zip && \
  rm autodl-irssi.zip && \
  cp autodl-irssi.pl autorun/ && \
  mkdir -p /config/.autodl
echo "[options]
gui-server-port = 12345
gui-server-password = notsosecretpassword" > /config/.autodl/autodl.cfg

echo "[options]
rt-address = /run/php/.rtorrent.sock" > /config/.autodl/autodl2.cfg

echo "/load perl" > /config/irssi/startup

# copy config
PREV_DIR=$(pwd)

cd /defaults/rutorrent-conf || exit
	for i in $(find . -type f)
 	do
		[[ ! -e "/config/rutorrent/settings/${i}" ]] && cp -v "${i}" "/config/rutorrent/settings/${i}"
 	done

cd "${PREV_DIR}" || exit

[[ ! -e /config/nginx/nginx.conf ]] && \
	cp /defaults/nginx.conf /config/nginx/nginx.conf


cp -pr /config/rutorrent/settings/* /usr/share/webapps/rutorrent/conf/

if [ ! -e "/config/php/php.ini" ]; then
	cp /etc/php7/php.ini /config/php/php.ini
	sed -i -e 's/\(register_argc_argv .*=\).*/\1 On/g' /config/php/php.ini
fi

cp /config/php/php.ini /etc/php7/php.ini

# create symlink for webui files
[[ ! -e /var/www/localhost/rutorrent ]] && ln -s \
/usr/share/webapps/rutorrent /var/www/localhost/rutorrent

# delete lock file if exists
[[ -e /config/rtorrent/rtorrent_sess/rtorrent.lock ]] && \
	rm /config/rtorrent/rtorrent_sess/rtorrent.lock

[[ ! -e /root/.autodl ]] && ln -s /config/.autodl /root/.autodl

# permissions
chown bytesized:bytesized \
	/data\
	/data{/completed,/downloading,/sessions,/watch}

chown -R bytesized:bytesized \
	/config \
	/run \
	/usr/share/webapps/rutorrent \
	/var/lib/nginx \
	/var/www/localhost/rutorrent

chmod -R 755 /config/rutorrent/profiles
chmod -R 755 /config/.htaccess
chown bytesized:bytesized /config/.htaccess

# Todo, can we do this differently?
chown -R bytesized:bytesized /root/
